Update 02_Functions.md
Kotlin/kotlin-by-example pull request #122
Opened 2020-10-19 06:34 UTC by Deep1307

Added code to print the result of function multiply and accordingly added the documentation line for it.

2020-10-19 06:39 UTC, Deep1307 commented on examples/01_introduction/02_Functions.md
> +    println(multiply(2, 4))                                             // 10
Added this line of code to Print the result of the function multiply.

2020-11-02 04:57 UTC, p7nov requested changes
Hi! 
Thank you for this improvement.
Please see my suggestion for simplifying the text.

2020-11-02 04:57 UTC, p7nov commented on examples/01_introduction/02_Functions.md
> +10. Prints the result of a function call (of function `multiply`).
Let's shorten the text a little: 

```suggestion
9. Prints the result of the `sum` function call.
10. Prints the result of the `multiply` function call.
```

2020-11-02 05:20 UTC, merged

2020-11-02 05:20 UTC, p7nov commented
Thanks!

2020-11-02 05:22 UTC, Deep1307 commented
> Thanks!

I am really glad to contribute. This is my first contribution so far. I am just getting started to contribute to the community.

2020-11-02 05:42 UTC, Deep1307 commented
> Thanks!

@p7nov  Can you tell me, How can I contribute more to the community and organization?

2020-11-02 06:03 UTC, p7nov commented
> > Thanks!
> 
> @p7nov Can you tell me, How can I contribute more to the community and organization?

It's always nice to hear such things from people!
There is a page [Contributing to Kotlin](https://kotlinlang.org/contribute.html) on kotlinlang.org. Here you can find ways to help the development of Kotlin.

2020-11-02 06:09 UTC, Deep1307 commented
> > > Thanks!
> > 
> > 
> > @p7nov Can you tell me, How can I contribute more to the community and organization?
> 
> It's always nice to hear such things from people!
> There is a page [Contributing to Kotlin](https://kotlinlang.org/contribute.html) on kotlinlang.org. Here you can find ways to help the development of Kotlin.

@p7nov  Thank You